### ISSUE TITLE
Internal Server Errorが出たり出なかったりする

### ISSUE THREAD

**Issue by DoiRyoto** [enpitut2023/IE_teacher#46]
https://ie-teacher-geek.vercel.app/result/5437a2d491c891fb2a19f999d7e6ff3676748ffd-8f70583f225a7fd29dde701c9408c4374ce767fe-8f3ea4c4374a59f2625a68e9498da03195f2efc0

リロードするとエラーが出たり出なかったりする。

**Comment by DoiRyoto** [comment]
[ERROR]	2023-08-02T13:34:09.653Z	b2d79465-cace-4798-a3b2-d008342b1e8e	Exception on /papers/5437a2d491c891fb2a19f999d7e6ff3676748ffd-8f70583f225a7fd29dde701c9408c4374ce767fe-8f3ea4c4374a59f2625a68e9498da03195f2efc0 [GET]
Traceback (most recent call last):
  File "/var/task/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/task/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/task/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/task/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "./api/index.py", line 50, in papers
    main_data = pc.get_paper_by_paperId(main_paper_id)
  File "/var/task/data/call_meta_paper.py", line 70, in get_paper_by_paperId
    r_dict = self.cut_none(json.loads(r)["data"]) # リスト型
  File "/var/lang/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/var/lang/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/var/lang/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 184 (char 183)

**Comment by DoiRyoto** [comment]
1本目の論文
「Scale-Aware Cartographic Displacement Based on Constrained Optimization」にエラーの原因がありそう

**Comment by xi-yangchun** [comment]
解決方法の案
https://github.com/enpitut2023/IE_teacher/commit/cae45558510995907c1640550894156a75d61e8d

**Comment by DoiRyoto** [comment]
POSTが制限で動かないので、とりあえずGETをFORで回す形で回避

**Comment by DoiRyoto** [comment]
API-KEY追加したら一旦は治りました
